### ISSUE TITLE
Floating icons

### ISSUE THREAD

**Issue by RankFTW** [Lyall/EiyudenChronicleRisingFix#1]
The floating icons that show interactions and enemy health information doesn't seem to match the location of the item it relates to unless it is in the centre of the screen. It's like the floating icons are stuck to the background until you match up the enemy with the location.

**Comment by Lyall** [comment]
I believe I have fixed this in the [latest release](https://github.com/Lyall/EiyudenChronicleRisingFix/releases) if you would like to give that a try.

**Comment by RankFTW** [comment]
> I believe I have fixed this in the [latest release](https://github.com/Lyall/EiyudenChronicleRisingFix/releases) if you would like to give that a try.

The new version fixes the issue. Thank you for taking the time Lyall.

**Comment by Lyall** [comment]
Awesome, closing the issue now.
