### ISSUE TITLE
Gog Version compability

### ISSUE THREAD

**Issue by ImperatorCHAOS** [Lyall/EiyudenChronicleRisingFix#3]
Hello, quick question i wanted to ask, is it working with gog version? Tried to copy everything in a game folder but it doesnt seem to work for me.
![NVIDIA_Share_dFjP6HJzyN](https://github.com/Lyall/EiyudenChronicleRisingFix/assets/39912058/0262755c-60f8-4ad0-b142-5987a9b6f822)

**Comment by Lyall** [comment]
I don't see why it wouldn't be compatible with the GOG version. Is BepInEx producing a log file in `BepInEx\Output.log`?

Edit: I'm just noticing you're trying to use the fix for Hundred Heroes. I have a dedicated fix for that game over [here.](https://github.com/Lyall/HundredHeroesFix)

**Comment by ImperatorCHAOS** [comment]
> I don't see why it wouldn't be compatible with the GOG version. Is BepInEx producing a log file in `BepInEx\Output.log`?
> 
> Edit: I'm just noticing you're trying to use the fix for Hundred Heroes. I have a dedicated fix for that game over [here.](https://github.com/Lyall/HundredHeroesFix)

Aww mate, my blind ass, sorry and thank for the advice, cheers <3
